version: '3'
services:
  web:
    build: .
    ports:
      - "30003:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lockpicking_db
      MYSQL_USER: ctf_user
      MYSQL_PASSWORD: ctf_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
